namespace:
  name: &namespace timhatdiehandandermaus

base_name: &basename plex-library-update-notifier

rbac:
  create: false

serviceaccount:
  name: *basename

role:
  name: *basename

rolebinding:
  name: *basename

configmaps:
  - name: *basename
    data:
      API_URL: "http://plex-resolver"
      BOT_TOKEN: __BOT_TOKEN__
      LAST_SEEN_CONFIGMAP_NAME: "plex-library-update-notifier-last-seen"
      LAST_SEEN_KEY_NAME: "LAST_SEEN"
      NAMESPACE: *namespace
  - name: plex-library-update-notifier-last-seen
    data:
      LAST_SEEN: "0"

secrets:
  - name: *basename
    data:
      BOT_TOKEN: __BOT_TOKEN__

cronjobs:
  - name: *basename
    image: ghcr.io/tim-hat-die-hand-an-der-maus/plex-library-update-notifier:__TAG__
    imagePullPolicy: Always
    schedule: "CRON_TZ=UTC * */1 * * *"
    backoffLimit: 0
    successfulJobsHistoryLimit: 1
    failedJobsHistoryLimit: 1
    restartPolicy: Never
    envFrom:
      configmaps:
        - *basename
        - plex-library-update-notifier-last-seen
      secrets:
        - *basename
    labels:
      app: *basename
    requests:
      cpu: 100m
      memory: 100Mi
    limit:
      cpu: 300m
      memory: 300Mi
