name: Build image

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - run: sed -i -e "s#__TAG__#${GITHUB_SHA}#g" values.yaml
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint --strict

  build_push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Build the tagged Docker image
        run: docker build -t ghcr.io/tim-hat-die-hand-an-der-maus/plex-library-update-notifier:${GITHUB_SHA} .
